### ISSUE TITLE
Apresentação e disposição a ajudar

### ISSUE THREAD

**Issue by mateus-amarante** [edromufu/edromufu#11]
Olá membros da EDROM. Ontem prestigiei a apresentação de vocês no Parque do Sabiá, o que me gerou muita nostalgia dos tempos de faculdade. Gostaria de me apresentar e me dispor a ajudá-los no que estiver ao meu alcance e no que potencialize o aprendizado de vocês.

Meu nome é Mateus, fui membro da EDROM de 2013 a 2015 e hoje trabalho com desenvolvimento de software para aplicações robóticas. Minha carreira profissional (e de outros colegas) se deve muito à minha experiência na EDROM. O contato com tecnologias de robótica e a dinâmica de trabalho em equipe foram elementos preparatórios e relevantes para a atuação no mercado de trabalho.

Ficaria feliz em compartilhar um pouco desta experiência no sentido de estimular o aprendizado e aprimorar a produtividade da equipe. Como minha especialidade é desenvolvimento de software, posso apoiar fazendo revisões de código ou até fazer algumas contribuições pontuais. Se quiserem, também podemos nos reunir para trocar conhecimento mais de perto.

Enfim, fiquem à vontade para entrarem em contato:

mateus.amarujo@gmail.com
https://www.linkedin.com/in/mateusamarante/

Atenciosamente,

Mateus.

**Comment by Martins-Lucaas** [comment]
Sou o Capitão da Equipe EDROM e gostaríamos de solicitar sua participação como consultor em nossa equipe, visando obter o benefício de sua experiência.
Neste momento crucial pré-competição, estamos cientes da importância de contar com orientação especializada para aprimorar nosso código e melhorar nosso desempenho geral. Por esse motivo, gostaríamos de marcar uma reunião com você e alguns diretores da equipe. Peço que me envie mensagem por favor nesse contato (34)998117344, para discutirmos sua disponibilidade
